[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/app/Dockerfile"
watchPatterns = ["packages/app/**", "api/**", "tailwind.config.js", "vite.config.ts", "package.json"]

[deploy]
startCommand = "npm run start:railway"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
